version: "3.9"

services:
  intel-nvidia-cuda-dev:
    profiles: ["wsl-nvidia-cuda"]
    ports:
      - "${NVIDIA_CUDA_HOST_PORT}:8888"
    build:
        context: .
        dockerfile: Dockerfile.intel-nvidia-cuda
    user: root
    volumes:
      - type: bind
        source: ${SOURCE_PATH}
        target: /home/workspace/${PROJECT_NAME}
      - type: bind
        source: ${DRIVE_PATH}
        target: /home/drive
        read_only: true
      - type : bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
        read_only: true
    working_dir: /home/workspace
    environment:
      PYTHONUNBUFFERED: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped    