version: "3.9"

services:
  wsl-intel-levelzero-opencl-xpu-dev:
    profiles: ["wsl-intel-levelzero-opencl-xpu"]
    build:
        context: .
        dockerfile: Dockerfile.intel-levelzero-opencl-xpu
    user: root
    volumes:
      - type: bind
        source: ${SOURCE_PATH}
        target: /home/workspace/${PROJECT_NAME}
      - type: bind
        source: ${DRIVE_PATH}
        target: /home/drive
        read_only: true
      - type : bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
        read_only: true
      - type : bind
        source : ${AI_COMPUTE_BENCHMARK_PATH}
        target : /home/workspace/ai-compute-benchmark
    environment:
      PYTHONUNBUFFERED: "1"
      LD_LIBRARY_PATH: "/usr/lib/wsl/lib"
      OMP_NUM_THREADS: "4"
      OPENBLAS_NUM_THREADS: "4"
      MKL_NUM_THREADS: "4"
      NUMEXPR_NUM_THREADS: "4"
    working_dir: /home/workspace
    devices:
      - /dev/dxg:/dev/dxg
    restart: unless-stopped
    