version: "3.9"

services:
  linux-nvidia-cuda-dev:
    profiles: ["linux-nvidia-cuda"]
    ports:
      - "${LINUX_NVIDIA_CUDA_HOST_PORT}:8888"
    build:
        context: .
        dockerfile: Dockerfile.intel-nvidia-cuda
    user: root
    volumes:
      - type: bind
        source: ${SOURCE_PATH}
        target: /home/workspace/${PROJECT_NAME}
      - type: bind
        source: ${DRIVE_PATH}
        target: /home/drive
        read_only: true
      - type : bind
        source : ${AI_COMPUTE_BENCHMARK_PATH}
        target : /home/workspace/ai-compute-benchmark
    working_dir: /home/workspace
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      PYTHONUNBUFFERED: "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped