version: "3.9"

services:
  wsl-intel-xpu-tensorflow-jupyter-dev:
    profiles: ["wsl-intel-xpu-tensorflow-jupyter"]
    ports:
      - "${TENSORFLOW_XPU_HOST_PORT}:8888"
    build:
        context: .
        dockerfile: Dockerfile.intel-opencl-levelzero-xpu-tensorflow-jupyter
    user: root
    volumes:
      - type: bind
        source: ${SOURCE_PATH}
        target: /home/workspace/${PROJECT_NAME}
      - type: bind
        source: ${DRIVE_PATH}
        target: /home/drive
        read_only: true
      - type : bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
        read_only: true
    environment:
      PYTHONUNBUFFERED: "1"
      LD_LIBRARY_PATH: "/usr/lib/wsl/lib"
    working_dir: /home/workspace
    devices:
      - /dev/dxg:/dev/dxg
    restart: unless-stopped
    