version: "3.9"

services:
  intel-tensorflow-xpu-dev:
    profiles: ["tensorflow-xpu"]
    container_name: intel-tensorflow-xpu-dev
    ports:
      - "8889:8889"
    build:
        context: .
        dockerfile: Dockerfile.intel-tensorflow-xpu
    user: root
    volumes:
      - type: bind
        source: ${SOURCE_PATH}
        target: /home/workspace/${PROEJCT_NAME}
      - type: bind
        source: ${DRIVE_PATH}
        target: /home/drive
        read_only: true
      - type : bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
        read_only: true
    environment:
      PYTHONUNBUFFERED: "1"
      LD_LIBRARY_PATH: "/usr/lib/wsl/lib"
    working_dir: /home/workspace
    devices:
      - /dev/dxg:/dev/dxg
    restart: unless-stopped
    